default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: chat_app_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: nhathuy
  password: 123456
  port: 5432
